#ifndef SEARCHGROUP_SEARCHROUP_H_
#define SEARCHGROUP_SEARCHROUP_H_

// SearchGroup lib import
#include "search.h"

#define SEARCHGROUP_INITIALIZA \
    SEARCH_INITIALIZA;


#endif//SEARCHGROUP_SEARCHROUP_H_
